# Generated by Django 4.1.5 on 2023-01-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waterorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grower', models.CharField(max_length=255)),
                ('acreage', models.FloatField()),
                ('croptype', models.CharField(max_length=255)),
                ('lifecycle', models.CharField(max_length=255)),
                ('cfs', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('soiltype', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
